name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 6 AM UTC to catch any issues early
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run comprehensive test suite
      run: |
        echo "Running full test suite with coverage reporting..."
        python -m pytest test_*.py -v --tb=short --cov=cat_flap_extractor_v5 --cov-report=term-missing --cov-fail-under=25
        
    - name: Test critical functions exist
      run: |
        echo "Verifying critical functions are accessible..."
        python -c "
        from cat_flap_extractor_v5 import ProductionCatFlapExtractor
        extractor = ProductionCatFlapExtractor()
        print('✅ ProductionCatFlapExtractor imported successfully')
        
        # Test critical functions exist
        critical_functions = [
            'process_pdf', 'parse_duration_hours', 'determine_single_timestamp_type',
            'extract_time_duration_pairs_by_day', 'build_sessions_with_enhanced_validation',
            'save_to_csv', 'save_to_json'
        ]
        
        for func in critical_functions:
            assert hasattr(extractor, func), f'Missing function: {func}'
            print(f'✅ {func} exists')
        
        print('✅ All critical functions verified')
        "
        
    - name: Validate requirements.txt
      run: |
        echo "Checking requirements.txt integrity..."
        pip check
        echo "✅ All dependencies are compatible"